FROM python:3.11-slim

RUN mkdir -p /container/scripts /container/input /container/output /container/db

COPY scripts/run_interpro_mapping.py /container/scripts/run_interpro_mapping.py

WORKDIR /container
